version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      M2_HOME: /opt/apache-maven
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - run:
          name: maven build
          command: |
            mvn -v
            mvn clean install
      - run:
          name: Install jFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Push to Artifactory
          command: |
            ./jfrog rt config --url=$ARTIFACTORY_URL --user=$ARTIFACTORY_USER --apikey=$ARTIFACTORY_APIKEY --interactive=false
            # ./jfrog rt mvn "clean install -f pom.xml" file.txt --build-name=pulse --build-number=$CIRCLE_BUILD_NUM
            # ./jfrog rt bce pulse $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
            # ./jfrog rt bp pulse $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory
            ./jfrog rt u pom.xml pulse-release
